Estrutura de Arquivos e README de Práticas
tecMTST/modelo-godot-3.6 pull request #2
Opened 2024-04-29 15:39 UTC by rodigu

Adicionei a estrutura de arquivos que foi decidina na reunião de ontem.

Acabei por remover o setup de build, perdão @nawarian .
Se tivermos que modificar o modelo que foi decidido por causa da build, de um toque.

As idéias principais são:

- Ter dois arquivos no root: o de exports e o de projeto. A Godot só estaria abrindo a pasta do projeto quando for rodar.
- Pastas em português, exceto addons (que é nome próprio para uso na Godot)

2024-04-29 16:35 UTC, nawarian commented
Camarada @rodigu eu não entendi o motivo de ter removido os arquivos do projeto e da build

2024-04-29 16:36 UTC, nawarian requested changes
Camarada @rodigu eu não entendi o motivo de ter removido os arquivos do projeto e da build. Vamos discutir antes de integrar o PR por favor :)

2024-04-29 16:47 UTC, rodigu commented
> Camarada @rodigu eu não entendi o motivo de ter removido os arquivos do projeto e da build. Vamos discutir antes de integrar o PR por favor :)

Removi pq não sei como mexer, postei aqui de pra justamente para reinserir os seu trâmites de build

2024-04-29 18:57 UTC, nawarian commented
Legal; vi que tu conseguiu trazer de volta o arquivo da build.

Como você colocou o projeto dentro da pasta `projeto/` em vez de deixar na raíz, vai precisar adicionar a opção `--path projeto/` no arquivo yaml do workflow. [Nessa linha aqui](https://github.com/tecMTST/modelo-godot-3.6/pull/2/commits/f4e8f7df92f7a2b38d709829e262bec0d26660b7#diff-20b882a0d09b6427478adf7a7cafc6b061d6ce1aa0871560e4c5bbaaf0d194b3R41).

Vai ficar algo assim:

```
godot --no-window --verbose --path projeto/ --export-debug "HTML5" dist/index.html
```

2024-04-30 01:52 UTC, rodigu commented
> Legal; vi que tu conseguiu trazer de volta o arquivo da build.
> 
> Como você colocou o projeto dentro da pasta `projeto/` em vez de deixar na raíz, vai precisar adicionar a opção `--path projeto/` no arquivo yaml do workflow. [Nessa linha aqui](https://github.com/tecMTST/modelo-godot-3.6/pull/2/commits/f4e8f7df92f7a2b38d709829e262bec0d26660b7#diff-20b882a0d09b6427478adf7a7cafc6b061d6ce1aa0871560e4c5bbaaf0d194b3R41).
> 
> Vai ficar algo assim:
> 
> ```
> godot --no-window --verbose --path projeto/ --export-debug "HTML5" dist/index.html
> ```

Seria tbm dentro de `exportados/web/index.html`, ao inves de `dist/index.html`?

2024-04-30 21:39 UTC, nawarian approved these changes

2024-04-30 21:39 UTC, nawarian commented on .vscode/settings.json
> +  "godotTools.editorPath.godot3": "/home/hiroto/Documents/godot/Godot_v3.6-beta3_x11.64"
Acho que é possível trocar `/home/hiroto` por `$HOME`. Talvez fosse interessante a gente padronizar o caminho do binário para algo como `/opt/godot-v3.6` ou `$HOME/.godot/godotv3.6`

2024-05-01 14:58 UTC, rodigu commented on .vscode/settings.json
> +  "godotTools.editorPath.godot3": "/home/hiroto/Documents/godot/Godot_v3.6-beta3_x11.64"
opa, perdao, o .vscode nao era pra ter ido junto
vou remover

2024-05-01 15:06 UTC, merged